### ISSUE TITLE
Deploy failed for daak-store - Netlify

### ISSUE THREAD

**Issue by daironreijna** [daironreijna/e-commerce-webstore#16]
3:17:35 PM: Could not resolve "./CartDropdown" from "src/Components/Navbar/navbar.jsx"
3:17:35 PM: file: /opt/build/repo/src/Components/Navbar/navbar.jsx
3:17:35 PM: error during build:
3:17:35 PM: RollupError: Could not resolve "./CartDropdown" from "src/Components/Navbar/navbar.jsx"
3:17:35 PM:     at error (file:///opt/build/repo/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
3:17:35 PM:     at ModuleLoader.handleInvalidResolvedId (file:///opt/build/repo/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
3:17:35 PM:     at file:///opt/build/repo/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
3:17:35 PM: ​
3:17:35 PM: "build.command" failed                                        
────────────────────────────────────────────────────────────────
3:17:35 PM:   Error message
3:17:35 PM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
3:17:35 PM: ​
3:17:35 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
3:17:35 PM: Failing build: Failed to build site
3:17:36 PM: Failed during stage "building site": Build script returned non-zero exit code: 2
3:17:36 PM: Finished processing build request in 16.338s

**Comment by daironreijna** [comment]
Above is a shortened version of the issue log.

**Comment by daironreijna** [comment]
Completed with assistance from tutor.
